### ISSUE TITLE
ENH?: Logging commands run in python

### ISSUE THREAD

**Issue by Eric89GXL** [ilogue/niprov#1]
I have a feeling I'm going to want to do things like this often:
```
        cmd = 'nibabel.load(in_name, scaling=scaling).save(out_name)'
        exec(cmd)
        niprov.log(cmd, parent=in_name, new=out_name)
```
It would be nicer if I could just directly do something like:
```
        niprov.run('nibabel.load(in_name, scaling=scaling).save(out_name)',
                  parent=in_name, new=out_name)
```
In other words, I wonder if it's possible to write a niprov function that can move itself back one stack frame to execute a bit of Python code. Not sure if this would be too unsafe or anything, though. We'd also want to make it so that if the command errored out, you would have gotten the same stack trace as you would have gotten just running the command directly (without wrapping in a string and passing it to `niprov.run`). @ilogue WDYT?

**Comment by ilogue** [comment]
I'm not a big fan of executing strings. How about something like this:

```
def analysis(scaling, in_name, out_name):
    nibabel.load(in_name, scaling=scaling).save(out_name)

niprov.record(analysis, scaling, in_name, out_name, parent=in_name, new=out_name)
```

or simply:
```
niprov.record(nibabel.load, scaling, in_name, out_name, parent=in_name, new=out_name)
```

Or maybe some variant where the args are in a list/dictionary to make it more readable:
or simply:
```
args = [scaling, in_name, out_name]
niprov.record(nibabel.load, args, parent=args[1], new=args[2])
```

**Comment by Eric89GXL** [comment]
The last two examples are incomplete because they unfortunately don't (can't) capture the chained nature of the commands. But it probably is more explicit to use a function def, so I can use the first one. Hopefully we don't have to construct too many dummy functions.

**Comment by ilogue** [comment]
I see what you mean. A code fragment instead of one operation. Yes let's keep this in mind and if it turns out to be tedious to wrap them we'll rethink this.
