### ISSUE TITLE
Got a new one

### ISSUE THREAD

**Issue by kambysese** [ilogue/niprov#100]
I'm not even going to try and decipher this one right now...

> Traceback (most recent call last):
>   File "/home/ktavabi/Projects/mnefun/examples/funloc/analysis_fun.py", line 114, in <module>
>     print_status=True,  # Print completeness status update
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 561, in do_processing
>     p.on_process(text, func, outs[ii], p)
>   File "/home/ktavabi/Projects/niprov/niprov/mnefunsupport.py", line 53, in handler
>     provenance.add(f, provenance=customprov)
>   File "/home/ktavabi/Projects/niprov/niprov/context.py", line 14, in add
>     return niprov.adding.add(filepath, **kwargs)
>   File "/home/ktavabi/Projects/niprov/niprov/adding.py", line 77, in add
>     repository.add(img)
>   File "/home/ktavabi/Projects/niprov/niprov/mongo.py", line 84, in add
>     self.db.provenance.insert_one(image.provenance)
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 625, in insert_one
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 530, in _insert
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 519, in _insert_one
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 458, in _legacy_write
>   File "build/bdist.linux-x86_64/egg/pymongo/pool.py", line 264, in legacy_write
>   File "build/bdist.linux-x86_64/egg/pymongo/helpers.py", line 235, in _check_gle_response
> pymongo.errors.DuplicateKeyError: E11000 duplicate key error index: niprov.provenance.$_id_  dup key: { : ObjectId('56c0fda0bb8b203600377f57') }

**Comment by ilogue** [comment]
I have an idea what's going on here. I think we are trying to insert a new record with an `_id` field in the provenance from another record. Can you open a PR on your progress with mnefunsupport so I can see the new code?

**Comment by kambysese** [comment]
Should I close this?

**Comment by ilogue** [comment]
If you're not seeing it anymore, yes
