### ISSUE TITLE
IO Error

### ISSUE THREAD

**Issue by kambysese** [ilogue/niprov#104]
I don't understand how `logging` is being evoked here for a `subj`not included in `params`.

> Traceback (most recent call last):
>   File "/home/ktavabi/Projects/ilabs/analysis_scripts/bad_baby/am_tone.py", line 92, in <module>
>     print_status=True
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 561, in do_processing
>     p.on_process(text, func, outs[ii], p)
>   File "/home/ktavabi/Projects/niprov/niprov/mnefunsupport.py", line 58, in handler
>     provenance.log(eventfile, 'scoring', rawfile, provenance=customprov)
>   File "/home/ktavabi/Projects/niprov/niprov/context.py", line 26, in log
>     return niprov.logging.log(*args, dependencies=self.deps, **kwargs)
>   File "/home/ktavabi/Projects/niprov/niprov/logging.py", line 97, in log
>     dependencies=dependencies)
>   File "/home/ktavabi/Projects/niprov/niprov/adding.py", line 68, in add
>     raise IOError(errno.ENOENT, 'File not found', filepath)
> IOError: [Errno 2] File not found: '/mnt/ALAYA/data/ilabs/bad_baby/tone/bad_120a/lists/ALL_bad_120a_am-eve.lst'

**Comment by kambysese** [comment]
@ilogue by any chance is this a quick fix?

**Comment by ilogue** [comment]
@kambysese  Are you working from home? Think this should be debugged in mnefunsupport. Check what files are being passed.

**Comment by ilogue** [comment]
Not so easy for me without the bad_baby script and/or data

**Comment by kambysese** [comment]
Uhg. Yeah I am working from home today.
