### ISSUE TITLE
Distinguish .fif files and use appropriate method to read them; MEG child files mis-categroized

### ISSUE THREAD

**Issue by kambysese** [ilogue/niprov#107]
Looks like logging is mis-identifying some files... Jut noting this so that I can hopefully take a look at later.

> Traceback (most recent call last):
>   File "/home/ktavabi/Projects/niprov/niprov/adding.py", line 70, in add
>     img.inspect()
>   File "/home/ktavabi/Projects/niprov/niprov/fif.py", line 23, in inspect
>     img = self.libs.mne.io.Raw(self.path, allow_maxshield=True)
>   File "<string>", line 2, in __init__
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 603, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/io/fiff/raw.py", line 97, in __init__
>     do_check_fname)
>   File "<string>", line 2, in _read_raw_file
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 603, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/io/fiff/raw.py", line 184, in _read_raw_file
>     raise ValueError('No raw data in %s' % fname)
> ValueError: No raw data in /mnt/ALAYA/data/ilabs/bad_baby/tone/bad_207/inverse/AM_tone_55-sss_eq_bad_207-ave.fif

**Comment by ilogue** [comment]
epochs:
* bads
* highpass
* lowpass
```
In [57]: out.info
Out[57]: 
<Info | 28 non-empty fields
    acq_pars : unicode | 20784 items
    bads : list | 0 items
    ch_names : list | MEG0113, MEG0112, MEG0111, MEG0122, MEG0123, MEG0121, ...
    chs : list | 369 items (ECG: 1, EOG: 2, EEG: 60, GRAD: 204, MAG: 102)
    comps : list | 0 items
    custom_ref_applied : bool | False
    description : unicode | 198 items
    dev_head_t : 'mne.transforms.Transform | 3 items
    dig : list | 216 items
    events : list | 1 items
    experimenter : unicode | 8 items
    file_id : dict | 4 items
    filename : str | /home/jasp.../test-epo.fif
    highpass : float | 0.10000000149 Hz
    hpi_meas : list | 1 items
    hpi_results : list | 1 items
    hpi_subsystem : dict | 3 items
    line_freq : float | 60.0
    lowpass : float | 40.0 Hz
    meas_date : numpy.ndarray | 2014-03-28 09:57:01
    meas_id : dict | 4 items
    nchan : int | 369
    proc_history : list | 2 items
    proj_id : numpy.ndarray | 1 items
    proj_name : unicode | 4 items
    projs : list | Average EEG reference: on, ...
    sfreq : float | 500.0 Hz
    subject_info : dict | 6 items
    acq_stim : NoneType
    ctf_head_t : NoneType
    dev_ctf_t : NoneType
    kit_system_id : NoneType
    xplotter_layout : NoneType
>

```
