### ISSUE TITLE
mongo db duplicate key error

### ISSUE THREAD

**Issue by kambysese** [ilogue/niprov#113]
Wouldn't a RT warning and skip work better than a hard error?

> Traceback (most recent call last):
>   File "/home/ktavabi/Projects/ilabs/analysis_scripts/bad_baby/am_tone.py", line 110, in <module>
>     print_status=True
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 561, in do_processing
>     p.on_process(text, func, outs[ii], p)
>   File "/home/ktavabi/Projects/niprov/niprov/mnefunsupport.py", line 54, in handler
>     provenance.add(f, provenance=customprov)
>   File "/home/ktavabi/Projects/niprov/niprov/context.py", line 14, in add
>     return niprov.adding.add(filepath, **kwargs)
>   File "/home/ktavabi/Projects/niprov/niprov/adding.py", line 77, in add
>     repository.add(img)
>   File "/home/ktavabi/Projects/niprov/niprov/mongo.py", line 84, in add
>     self.db.provenance.insert_one(image.provenance)
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 625, in insert_one
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 530, in _insert
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 519, in _insert_one
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 458, in _legacy_write
>   File "build/bdist.linux-x86_64/egg/pymongo/pool.py", line 264, in legacy_write
>   File "build/bdist.linux-x86_64/egg/pymongo/helpers.py", line 235, in _check_gle_response
> pymongo.errors.DuplicateKeyError: E11000 duplicate key error index: niprov.provenance.$_id_  dup key: { : ObjectId('56eafc54bb8b201ce7b48f47') }

**Comment by ilogue** [comment]
What's an RT warning?

**Comment by kambysese** [comment]
`RuntimeWarning`

**Comment by ilogue** [comment]
Are you in? 

I see what's happening. We are re-using the dictionary for subjects (in the loop). So after adding the first subject, it has a database id. Instead, we should copy `customprov` using the `copy` module,
or recreate `customprov` for each subject.
```
customprov = {'mnefun':paramdict}
```

**Comment by kambysese** [comment]
I am downstairs

**Comment by ilogue** [comment]
Two fixes needed:

* mnefunsupport creates a fresh `customprov` for every subject
* detect this problem in niprov and raise a more user-friendly error
