### ISSUE TITLE
import niprov fails in script but works in ipython

### ISSUE THREAD

**Issue by mrjeffs** [ilogue/niprov#133]
weird:
Traceback (most recent call last):
  File "pylabs/tadpole_qt1_comparison.py", line 3, in <module>
    from pylabs.utils.paths import getlocaldataroot
  File "/home/toddr/Software/pylabs/pylabs/__init__.py", line 5, in <module>
    from . import utils
  File "/home/toddr/Software/pylabs/pylabs/utils/__init__.py", line 7, in <module>
    from ._options import PylabsOptions  # noqa
  File "/home/toddr/Software/pylabs/pylabs/utils/_options.py", line 1, in <module>
    import niprov
  File "/home/toddr/Software/niprov/niprov/__init__.py", line 11, in <module>
    from niprov.webapp import serve
  File "/home/toddr/Software/niprov/niprov/webapp.py", line 1, in <module>
    from pyramid.config import Configurator
  File "/home/toddr/Software/anaconda2/lib/python2.7/site-packages/pyramid/config/__init__.py", line 10, in <module>
    from webob.exc import WSGIHTTPException as WebobWSGIHTTPException
  File "/home/toddr/Software/anaconda2/lib/python2.7/site-packages/webob/__init__.py", line 2, in <module>
    from webob.request import *
  File "/home/toddr/Software/anaconda2/lib/python2.7/site-packages/webob/request.py", line 1500, in <module>
    class LimitedLengthFile(io.RawIOBase):
AttributeError: 'module' object has no attribute 'RawIOBase'

**Comment by ilogue** [comment]
Any changes in your environment? The error suggests a version conflict.

**Comment by ilogue** [comment]
Oh you are in the pylabs directory which has an `io` package which is the conflict:

http://stackoverflow.com/questions/23572003/why-io-module-object-has-no-attribute-rawiobase-eventhough-i-am-using-python-2

**Comment by ilogue** [comment]
Try `cd ..`

**Comment by ilogue** [comment]
If that doesn't help we can rename the `pylabs.io` package

**Comment by mrjeffs** [comment]
None that I can tell. Just nibabel. As far as I know. How would I tell which is the offending package? J


From: "Jasper J.F. van den Bosch"
Reply-To: ilogue/niprov
Date: Friday, April 15, 2016 at 6:36 PM
To: ilogue/niprov
Cc: Jeff Stevenson
Subject: Re: [ilogue/niprov] import niprov fails in script but works in ipython (#133)


Any changes in your environment? The error suggests a version conflict.

**Comment by mrjeffs** [comment]
Well then. I was simply following where you put your script. Why did you put it there instead of in qt1? Just curious… j


From: "Jasper J.F. van den Bosch"
Reply-To: ilogue/niprov
Date: Friday, April 15, 2016 at 6:38 PM
To: ilogue/niprov
Cc: Jeff Stevenson
Subject: Re: [ilogue/niprov] import niprov fails in script but works in ipython (#133)


Try cd ..

**Comment by ilogue** [comment]
Also, try not to use relative imports (`from . import utils`)

**Comment by ilogue** [comment]
You can still put it in the qt1 location but run the code with your working directory elsewhere.

**Comment by ilogue** [comment]
`import pylabs.utils as utils` should fix it too.

**Comment by mrjeffs** [comment]
How about just moving the script into the qt1 dir? J


From: "Jasper J.F. van den Bosch"
Reply-To: ilogue/niprov
Date: Friday, April 15, 2016 at 6:39 PM
To: ilogue/niprov
Cc: Jeff Stevenson
Subject: Re: [ilogue/niprov] import niprov fails in script but works in ipython (#133)


If that doesn't help we can rename the pylabs.io package

**Comment by mrjeffs** [comment]
Right, usually I run everything from ~/Software/pylabs. As in
Python pylabs/qt1/pipeline.py

From: "Jasper J.F. van den Bosch"
Reply-To: ilogue/niprov
Date: Friday, April 15, 2016 at 6:41 PM
To: ilogue/niprov
Cc: Jeff Stevenson
Subject: Re: [ilogue/niprov] import niprov fails in script but works in ipython (#133)


You can still put it in the qt1 location but run the code with your working directory elsewhere.

**Comment by mrjeffs** [comment]
Ok will try that 1st. J


From: "Jasper J.F. van den Bosch"
Reply-To: ilogue/niprov
Date: Friday, April 15, 2016 at 6:41 PM
To: ilogue/niprov
Cc: Jeff Stevenson
Subject: Re: [ilogue/niprov] import niprov fails in script but works in ipython (#133)


import pylabs.utils as utils should fix it too.

**Comment by mrjeffs** [comment]
I don’t usually. :-) j


From: "Jasper J.F. van den Bosch"
Reply-To: ilogue/niprov
Date: Friday, April 15, 2016 at 6:40 PM
To: ilogue/niprov
Cc: Jeff Stevenson
Subject: Re: [ilogue/niprov] import niprov fails in script but works in ipython (#133)


Also, try not to use relative imports (from . import utils)

**Comment by mrjeffs** [comment]
Nope not working. Seems the __init__ in pylabs is in conflict no? J


From: "Jasper J.F. van den Bosch"
Reply-To: ilogue/niprov
Date: Friday, April 15, 2016 at 6:41 PM
To: ilogue/niprov
Cc: Jeff Stevenson
Subject: Re: [ilogue/niprov] import niprov fails in script but works in ipython (#133)


import pylabs.utils as utils should fix it too.

**Comment by ilogue** [comment]
I'm closing this as it's a pylabs issue
