### ISSUE TITLE
Mongo db error

### ISSUE THREAD

**Issue by kambysese** [ilogue/niprov#171]
So this happened with the handler

> /home/ktavabi/Projects/niprov/niprov/fif.py:24: DeprecationWarning: add_eeg_ref defaults to True in 0.13, will default to False in 0.14, and will be removed in 0.15. We recommend to use add_eeg_ref=False and set_eeg_reference() instead.
>   img = self.libs.mne.io.Raw(self.path, allow_maxshield=True)
> Traceback (most recent call last):
>   File "/home/ktavabi/Projects/shiva/shiva/process.py", line 163, in <module>
>     print_status=True
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 594, in do_processing
>     p.on_process(text, func, outs[ii], p)
>   File "/home/ktavabi/Projects/niprov/niprov/mnefunsupport.py", line 70, in handler
>     provenance.log(pcafile, trans, sssfile, provenance=customprov)
>   File "/home/ktavabi/Projects/niprov/niprov/context.py", line 54, in log
>     transient, script, user, provenance, opts, self.deps)
>   File "/home/ktavabi/Projects/niprov/niprov/logging.py", line 88, in log
>     dependencies=dependencies)
>   File "/home/ktavabi/Projects/niprov/niprov/adding.py", line 93, in add
>     repository.update(img)
>   File "/home/ktavabi/Projects/niprov/niprov/mongo.py", line 65, in update
>     self.deflate(image))
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 2244, in update
>   File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 715, in _update
>   File "build/bdist.linux-x86_64/egg/pymongo/pool.py", line 244, in command
>   File "build/bdist.linux-x86_64/egg/pymongo/pool.py", line 372, in _raise_connection_failure
> bson.errors.InvalidDocument: Cannot encode object: array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

**Comment by ilogue** [comment]
Looks like there is an array in the params object that we are not decoding
to a list

**Comment by kambysese** [comment]
Oh, that must be `params.subject_indices`

**Comment by kambysese** [comment]
`params.subject_indices` is always an (N, ) array

**Comment by ilogue** [comment]
Weird it should be caught by line 41 in mnefunsupport. I'll fix this later
today

**Comment by ilogue** [comment]
I can't replicate this. Is your mnefunsupport altered? Maybe best if we look together sometime

**Comment by ilogue** [comment]
Think we haven't seen this in a while, right @kambysese? Closing it for now

**Comment by kambysese** [comment]
IIRC this was squashed
