### ISSUE TITLE
how to store one or more object contents when logging

### ISSUE THREAD

**Issue by mrjeffs** [ilogue/niprov#176]
how do i pass some object(s) info associated with a processing step to the prov db? not the files, stuff like **kwargs etc...

**Comment by ilogue** [comment]
Use the `provenance` argument:

```python
log(new, transformation, parents, provenance={'myData':mydict})
```

But the dictionary passed can not contain objects from custom classes; MongoDB does not know how to store these. Instead, convert then to a dictionary somehow.

**Comment by mrjeffs** [comment]
that seemed to work. i saw the object name and contents in the db. well done!
