### ISSUE TITLE
niprov crashes with nrrd file conversion

### ISSUE THREAD

**Issue by mrjeffs** [ilogue/niprov#177]
tried to provenize my nrrd conversion tool but got this traceback:
    nii2nrrd(str(ten_fname)+'.nii.gz', str(ten_fname)+'.nhdr', istensor=True)
  File "/home/toddr/Software/pylabs/pylabs/conversion/nifti2nrrd.py", line 64, in nii2nrrd
    provenance.log(nrrd_fname, 'convert nii to nrrd using pynrrd', niftifile, script=__file__, provenance=options)
  File "/home/toddr/Software/niprov/niprov/context.py", line 54, in log
    transient, script, user, provenance, opts, self.deps)
  File "/home/toddr/Software/niprov/niprov/logging.py", line 66, in log
    parents = [location.completeString(p) for p in parents]
TypeError: 'PosixPath' object is not iterable

can nrrd be supported using pynrrd?

**Comment by ilogue** [comment]
I think that `pylabs.conversion.nifti2nrrd` is passing a `PosixPath` object to `log()`, perhaps from another library? I'll know more when I see `nifti2nrrd`

**Comment by mrjeffs** [comment]
it should be a string type path and file name passed to niprov.log: 
`ten_fname = str(tenpath / str(fdwi_basen + '_' + m.lower() + '_cam2fsl_tensor'))
nii2nrrd(ten_fname + '.nii.gz', ten_fname + '.nhdr', istensor=True)`
eg '/dir1/dir2/dir3/filename.nii.gz' as parent and '/dir1/dir2/dir3/filename.nhdr' as new file

**Comment by ilogue** [comment]
``niftifile = Path(niftifile)``

This line creates the PosixPath that is then passed to niprov. The quick fix is to pass str(niftifile) instead.

**Comment by ilogue** [comment]
What is the benefit of pathlib? Do you think its useful to  implement support for it in Niprov.

**Comment by mrjeffs** [comment]
that fixed it, my bad. a little more info on which file failed would have been nice. jusr sayin'.
pathlib is useful for making symbolic links and makes and tests dirs and paths easier than os.
