### ISSUE TITLE
provenance serve crashes

### ISSUE THREAD

**Issue by mrjeffs** [ilogue/niprov#181]
serving on http://0.0.0.0:6543
/home/toddr/Software/nibabel/nibabel/cifti2/parse_cifti2.py:24: FutureWarning: We no longer carry a copy of the 'six' package in nibabel; Please import the 'six' package directly
  from ..externals.six import BytesIO

[3]+  Segmentation fault      (core dumped) provenance serve

six in base conda install. not sure what the complaint is.

**Comment by JasperVanDenBosch** [comment]
Try reinstalling nibabel, or upgrading:
```
pip install -U nibabel
```
If you do `pip freeze` does it list six?

**Comment by mrjeffs** [comment]
yes
pip freeze | grep six
six==1.10.0
and 
nibabel==2.2.0.dev0
the latest pull from github master
and now it works! the last nibabel pull was 2-3 days ago. so maybe a bug that got fixed?? weird...

**Comment by JasperVanDenBosch** [comment]
Great!
