### ISSUE TITLE
[ENH] FIF provenance custom header field

### ISSUE THREAD

**Issue by ilogue** [ilogue/niprov#2]
Hi @Eric89GXL, could you look into what would be an appropriate field in the FIF format to attach provenance? So far I was looking at `FIFF.FIFF_PROJ_COMMENT      = 504` but I think you mentioned there might be a better one.

Here is the list with constants:

https://github.com/mne-tools/mne-python/blob/master/mne/io/constants.py

**Comment by Eric89GXL** [comment]
In `mnefun` I use what is a reasonable entry point to store the channel reordering information, see:

https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L663

If you're really interested to figure out where that dictionary key/value effectively gets stored in the FIFF file and the corresponding FIFF constant, you or I can dig through `mne.io.meas_info` to figure it out -- but hopefully mne-python provides a sufficiently convenient API that we won't need to.

**Comment by ilogue** [comment]
Are you saying I could append it to `info['description']`? It wouldn't get in the way of `mnefun`'s use of `info['description']`?

**Comment by Eric89GXL** [comment]
As long as it's appended and not overwritten it should be okay. You might need to make sure the `fix_eeg_channels` plays nicely / respects whatever other information is already in there, too. I think up to now I've assumed that I could write to that field for that function without needing to preserve other information.

**Comment by ilogue** [comment]
Yes I think `fix_eeg_channels` would erase anything else, but that is not an issue because if mnefun plays with the file, it's safe to assume that it has changed so we need to update provenance anyway.

Thanks!

**Comment by ilogue** [comment]
For future reference, here is where the reordering info gets written:

https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L687
