### ISSUE TITLE
Web app / browsing interface

### ISSUE THREAD

**Issue by ilogue** [ilogue/niprov#23]
**instant mode**
Serve in foreground and launch browser
```
provenance browse
```
**server mode**
Serve in background
```
provenance serve
```
Use pyramid.scripts.pserve with niprov.cfg.

**URL design**
```
niprov.ilabs.edu/location/apollo/home/jasperb/data/myproject/mri/blabla.nii.gz
niprov.ilabs.edu/id/Yus3HwsP
niprov.ilabs.edu/subject/johndoe/
niprov.ilabs.edu/statistics/
niprov.ilabs.edu/latest/
```

**Comment by ilogue** [comment]
Any ideas, tips, comments? @mrjeffs @kambysese ?

**Comment by kambysese** [comment]
What is the delivery in <i>server mode</i>?
Re: URL design how about `niprov.ilabs.edu/subject/johndoe/${qualifier}`?

**Comment by ilogue** [comment]
It's completely the same, except it's in background and no browser is started for you, assuming you will be running it indefinitely and from any browser anywhere, whereas the other mode is for inmediate use (although it would also be accessible from other browsers)

Additional qualifiers sounds good. What did you have in mind? 

As a next step ofcourse we could also have;

```
niprov.ilabs.edu/modality/meg/
```
or
```
niprov.ilabs.edu/filetype/nifti/
```

**Comment by ilogue** [comment]
Does justin have a github account?

**Comment by kambysese** [comment]
He should. I need to see this thing in action before I can feel any more useful; but I am thinking that qualifier may include modality or milestone events e.g., statistics. Re:mode than +1 for instant.

**Comment by ilogue** [comment]
@ilabsbrainteam
