### ISSUE TITLE
useful header info to store from PAR file nibabel conversion

### ISSUE THREAD

**Issue by mrjeffs** [ilogue/niprov#48]
General info fields to add are:
Technique
Repetition Time
FOV
MTC
EPI
Diffusion
from image info:
number of dynamics (as in largest value in dynamic scan number)
slice thickness
slice orientation
echo time(s) - could be multiple - just 1 of each
image flip angle(s)  - could be multiple - just 1 of each
Inversion delay(s)  - could be multiple - just 1 of each

it would be good to organize the web display into technique, resolution, and contrast groupings.
j

**Comment by ilogue** [comment]
@mrjeffs
Can you add a screenshot of the header, so I have the full key names of
these fields?

**Comment by ilogue** [comment]
This might help me for the full names

http://www.mathworks.com/matlabcentral/fileexchange/29344-read-medical-data-3d/content/par/par_read_header.m

**Comment by ilogue** [comment]
Also see https://github.com/nipy/nibabel/blob/master/nibabel/parrec.py
