### ISSUE TITLE
niprov connection/context/manager object

### ISSUE THREAD

**Issue by ilogue** [ilogue/niprov#5]
object serves as interface, instead of the base module, on which to call interface methods.

```
from niprov import NiprovContext

niprov = NiprovContext()
niprov.log(x,y,z)
```

instead of

```
import niprov
niprov.log(x,y,z)
```

This means we have to set global settings only once and can test for a connection, etc.

**Comment by ilogue** [comment]
```python
# current
import niprov
options = niprov.options()
niprov.log(options)
options.x = y
niprov.log(options)

# new design
import niprov
provenance = niprov.Context()
provenance.log()
provenance.options.verbose = True
provenance.log()

# option 1
provenance = niprov.Context()
provenance.config.verbose = True

# option 1
provenance = niprov.Context()
provenance.settings.verbose = True

# option 1
provenance = niprov.Context()
provenance.options.verbose = True

# option 1
provenance = niprov.Context()
context.settings.verbose = True

etc etc
```

In other words, what should the `Context` object be called and what should the `Configuration` object be called?

@mrjeffs @kambysese

**Comment by kambysese** [comment]
I prefer option A3.

**Comment by ilogue** [comment]
Jeff likes A3 too but has no strong preference

**Comment by kambysese** [comment]
A3 makes the most sense to me from users end

**Comment by ilogue** [comment]
Yeah I see what you mean. The class is called `Configuration` so from a
developer view I'd prefer `config`. I'll go with that for now and we'll see
when we have more code whether it feel really wrong.
