### ISSUE TITLE
test same file names from diff hosts with sha1

### ISSUE THREAD

**Issue by mrjeffs** [ilogue/niprov#92]
track same files used by different hosts as same file if sha1 is identical. like adding branck to file history

**Comment by ilogue** [comment]
I think this is very interesting but I'm wondering how to approach it. If you create a new file from the file copy on machine B, and another file from the copy on machine A, do they have the same parent? This could potentially get confusing.

I also wonder how niprov will know about the copy? When is it added?

**Comment by ilogue** [comment]
One option, which would be a major change, is to start using uuids to identify records, and have `location` be a list, and `hash` an optional field.

**Comment by ilogue** [comment]
Another issue here is that hash-equality doesn't necessarily mean the file is a copy.

Let me paint a scenario here. You run a script, version 1, and create file A. You now change the script, to version 2, but it creates a file that is the same, with the same hash, file B. You probably wouldn't want niprov to see this as a "copy."

**Comment by ilogue** [comment]
![img_20160205_152238](https://cloud.githubusercontent.com/assets/1508492/12862067/f756dd7c-cc1c-11e5-81c2-36d68152a0cf.jpg)
![img_20160205_152258](https://cloud.githubusercontent.com/assets/1508492/12862072/ff2a633e-cc1c-11e5-8028-2667ca8355b5.jpg)

**Comment by ilogue** [comment]
If the newly added file has been created by i.e. log(), and therefore is genuinely a new file for provenance, we can have a flag, that suppresses considering it as a copy

**Comment by ilogue** [comment]
When looking for a parent of it doesn't exist just add it

**Comment by ilogue** [comment]
If no parent, look for copies to get inheritable fields etc

**Comment by ilogue** [comment]
empty files will look like copies

**Comment by ilogue** [comment]
store `copy-of` location for reference

**Comment by ilogue** [comment]
Make `inheritFrom()` a method so that `add()` can do what `log()` is doing
